brew "qlcolorcode"
brew "qlstephen"
brew "qlmarkdown"
brew "quicklook-json"
brew "qlimagesize"
brew "suspicious-package"
brew "apparency"
brew "quicklookase"
brew "qlvideo"

brew "git"
brew "tmux"
brew "fish"
brew "svn"
brew "isacikgoz/taps/tldr"
brew "yank"
brew "parallele"
brew "httpie"
brew "exa"
brew "fzf"
brew "git-delta"
brew "ripgrep"
brew "fd"
brew "bat"
brew "terminal-notifier"

cask "notion"
cask "typora"
cask "raycast"
cask "alacritty"
cask "visual-studio-code"
cask "zoom"
cask "1password"
cask "1password/tap/1password-cli"
cask "authy"

brew "kubectl"
brew "helm"
brew "kubie"
cask "google-cloud-sdk"
cask "docker"

tap "snyk/tap"
brew "snyk"

tap "homebrew/cask-fonts"
brew "font-inconsolata"
brew "font-fira-code"
brew "font-inconsolata-g-for-powerline"
brew "font-inconsolata-lgc-nerd-font"

brew "homebrew/cask-drivers/logitech-options"
