brew "qlcolorcode"
cask "qlstephen"
brew "qlmarkdown"
brew "quicklook-json"
cask "qlimagesize"
brew "suspicious-package"
brew "apparency"
brew "quicklookase"
brew "qlvideo"

brew "git"
brew "tmux"
brew "fish"
brew "fisher"
brew "svn"
brew "isacikgoz/taps/tldr"
brew "yank"
brew "parallel"
brew "httpie"
brew "exa"
brew "fzf"
brew "git-delta"
brew "ripgrep"
brew "fd"
brew "bat"
brew "terminal-notifier"
brew "starship"

cask "notion"
cask "typora"
cask "raycast"
cask "alacritty"
cask "visual-studio-code"
cask "zoom"
cask "1password"
cask "1password/tap/1password-cli"
cask "authy"

brew "kubectl"
brew "helm"
brew "kubie"
cask "google-cloud-sdk"
cask "docker"

tap "snyk/tap"
brew "snyk"

tap "homebrew/cask-fonts"
cask "font-inconsolata"
cask "font-fira-code"
cask "font-inconsolata-g-for-powerline"
cask "font-inconsolata-lgc-nerd-font"

tap "homebrew/cask-drivers"
cask "homebrew/cask-drivers/logitech-options"
