[[actions]]
name = "create-pr"
desc = "Create PR"
lua = '''
  exec_shell("jj pr")
'''

[[bindings]]
action = "create-pr"
seq = ["g", "p"]
scope = "revisions"
desc = "Create PR"

[[actions]]
name = "move-commit-down"
desc = "Move commit down"
lua = '''
  local id = context.change_id()
  if id then
    local _, err = jj({"rebase", "-r", id, "--insert-before", id .. "-"})
    if err then flash("Error: " .. err) else revisions.refresh({}) end
  end
'''

[[bindings]]
action = "move-commit-down"
seq = ["m", "j"]
scope = "revisions"
desc = "Move commit down"

[[actions]]
name = "move-commit-up"
desc = "Move commit up"
lua = '''
  local id = context.change_id()
  if id then
    local _, err = jj({"rebase", "-r", id, "--insert-after", id .. "+"})
    if err then flash("Error: " .. err) else revisions.refresh({}) end
  end
'''

[[bindings]]
action = "move-commit-up"
seq = ["m", "k"]
scope = "revisions"
desc = "Move commit up"

[[actions]]
name = "delta-diff"
desc = "Show diff with delta"
lua = '''
  local id = context.change_id()
  if id then
    exec_shell("jj show -r " .. id .. " --summary --git --color=always | delta --pager 'less -R'")
  end
'''

[[bindings]]
action = "delta-diff"
seq = ["g", "d"]
scope = "revisions"
desc = "Show diff with delta"
